<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE pdr [
  <!ELEMENT pdr (section+)>
  <!ELEMENT section (rule+)>
  <!ELEMENT rule (#PCDATA|term)*>
  <!ATTLIST section number CDATA #REQUIRED>
  <!ATTLIST section name CDATA #REQUIRED>
  <!ATTLIST rule number CDATA #REQUIRED>
  <!ELEMENT term (#PCDATA)>
  <!ATTLIST term name CDATA #REQUIRED>
]>
<pdr>
  <section number="1" name="Загальні положення">
    <rule number="1.1">
      Ці Правила відповідно до Закону України «Про дорожній рух» встановлюють єдиний порядок дорожнього руху на всій території України.
      Інші нормативні акти, що стосуються особливостей дорожнього руху (перевезення спеціальних вантажів, експлуатація транспортних засобів окремих видів, рух на закритій території тощо), повинні ґрунтуватися на вимогах цих Правил.
    </rule>
    <rule number="1.2">
      В Україні установлено правосторонній рух транспортних засобів.
    </rule>
    <rule number="1.3">
      Учасники дорожнього руху зобов'язані знати й неухильно виконувати вимоги цих Правил, а також бути взаємно ввічливими.
    </rule>
    <rule number="1.4">
      Кожний учасник дорожнього руху має право розраховувати на те, що й інші учасники виконують ці Правила.
    </rule>
    <rule number="1.5">
      Дії або бездіяльність учасників дорожнього руху та інших осіб не повинні створювати небезпеку чи перешкоду для руху, загрожувати життю або здоров'ю громадян, завдавати матеріальних збитків.
      Особа, яка створила такі умови, зобов'язана негайно вжити заходів до забезпечення безпеки дорожнього руху на цій ділянці дороги та вжити всіх можливих заходів до усунення перешкод, а якщо це неможливо, попередити про них інших учасників дорожнього руху, повідомити підрозділ міліції, власника дороги або уповноважений ним орган.
    </rule>
    <rule number="1.6">
      Використовувати дороги не за їх призначенням дозволяється з урахуванням вимог статей 36-38 Закону України «Про автомобільні дороги».
    </rule>
    <rule number="1.7">
      Водії, пішоходи та пасажири зобов'язані бути особливо уважними до таких категорій учасників дорожнього руху, як діти, люди похилого віку та особи з явними ознаками інвалідності.
    </rule>
    <rule number="1.8">
      Обмеження в дорожньому русі, крім передбачених цими Правилами, можуть бути запроваджені в установленому законодавством порядку.
    </rule>
    <rule number="1.9">
      Особи, які порушують ці Правила, несуть відповідальність згідно із законодавством.
    </rule>
    <rule number="1.10">
      Терміни, що наведені у цих Правилах, мають таке значення:
      <term name="автобус">втомобіль з кількістю місць для сидіння більше дев'яти з місцем водія включно, який за своєю конструкцією та обладнанням призначений для перевезення пасажирів та їхнього багажу із забезпеченням необхідного комфорту та безпеки;</term>
      <term name="автомагістраль">
        спеціально побудована і призначена для руху транспортних засобів, не призначена для в’їзду на прилеглу територію або виїзду з неї;
        має для кожного напрямку руху окремі проїзні частини, відокремлені одна від іншої розділювальною смугою;
        не перетинає на одному рівні інші дороги, залізничні і трамвайні колії, пішохідні і велосипедні доріжки, шляхи проходу тварин, має огородження на узбіччях і розділювальній смузі та обгороджена сіткою;
        позначена дорожнім знаком 5.1
      </term>
      <term name="автомобільна дорога">
        вулиця (дорога) — частина території, в тому числі в населеному пункті, призначена для руху транспортних засобів і пішоходів, з усіма розташованими на ній спорудами (мостами, шляхопроводами, естакадами, надземними і підземними пішохідними переходами) та засобами організації дорожнього руху, і обмежена по ширині зовнішнім краєм тротуарів чи краєм смуги відводу. Цей термін включає також спеціально побудовані тимчасові дороги, крім довільно накатаних доріг (колій);
      </term>
      <term name="автомобільні дороги державного значення">
        автомобільні дороги загального користування, до яких належать міжнародні, національні та регіональні автомобільні дороги, які позначені відповідними дорожніми знаками;
      </term>
      <term name="автопоїзд (транспортний состав)">
        механічний транспортний засіб, що з’єднаний з одним або кількома причепами за допомогою зчіпного пристрою
      </term>
      <term name="безпечна дистанція">
        відстань до транспортного засобу, що рухається попереду по тій самій смузі, яка у разі його раптового гальмування або зупинки дасть можливість водієві транспортного засобу, що рухається позаду, запобігти зіткненню без здійснення будь-якого маневру;
      </term>
      <term name="безпечний інтервал">
        відстань між боковими частинами транспортних засобів, що рухаються, або між ними та іншими об'єктами, за якої гарантована безпека дорожнього руху;
      </term>
      <term name="безпечна швидкість">
        швидкість, за якої водій має змогу безпечно керувати транспортним засобом та контролювати його рух у конкретних дорожніх умовах;
      </term>
      <term name="буксирування">
        переміщення одним транспортним засобом іншого транспортного засобу, яке не належить до експлуатації автопоїздів (транспортних составів) на жорсткому чи гнучкому зчепленні або способом часткового навантаження на платформу чи на спеціальне опорне пристосування;
      </term>
      <term name="вантажний автомобіль">
        автомобіль, який за своєю конструкцією та обладнанням призначений для перевезення вантажів;
      </term>
      <term name="велосипед">
        транспортний засіб, крім інвалідних колясок, що приводиться в рух мускульною силою людини, яка знаходиться на ньому;
      </term>
      <term name="велосипедист">
        особа, яка керує велосипедом
      </term>
      <term name="велосипедна доріжка">
        виконана в межах дороги чи поза нею доріжка з покриттям, що призначена для руху на велосипедах і позначена дорожнім знаком 4.12
      </term>
      <term name="видимість у напрямку руху">
        максимальна відстань, на якій з місця водія можна чітко розпізнати межі елементів дороги та розміщення учасників руху, що дає змогу водієві орієнтуватися під час керування транспортним засобом, зокрема для вибору безпечної швидкості та здійснення безпечного маневру;
      </term>
      <term name="вимушена зупинка">
        припинення руху транспортного засобу через його технічну несправність чи небезпеку, яка спричинена вантажем, який перевозиться, станом учасника дорожнього руху, появою перешкоди для руху;
      </term>
      <term name="випередження">
        рух транспортного засобу із швидкістю, що перевищує швидкість попутного транспортного засобу, що рухається поряд по суміжній смузі;
      </term>
      <term name="власник транспортного засобу">
        фізична або юридична особа, яка володіє майновими правами на транспортний засіб, що підтверджується відповідними документами;
      </term>
      <term name="водій">
        особа, яка керує транспортним засобом і має посвідчення водія (посвідчення тракториста-машиніста, тимчасовий дозвіл на право керування транспортним засобом, тимчасовий талон на право керування транспортним засобом) відповідної категорії. Водієм також є особа, яка навчає керуванню транспортним засобом, перебуваючи безпосередньо в транспортному засоб
      </term>
      <term name="габаритно-ваговий контроль">
        перевірка габаритних і вагових параметрів транспортного засобу (в тому числі механічного транспортного засобу), причепу і вантажу на предмет відповідності встановленим нормам щодо габаритів (ширина, висота від поверхні дороги, довжина транспортного засобу) та щодо навантаження (фактична маса, осьове навантаження), яка проводиться відповідно до встановленого порядку на стаціонарних або пересувних пунктах габаритно-вагового контролю;
      </term>
      <term name="газон">
        ділянка однорідної території із дерновим покривом, який штучно створюється шляхом посіву і вирощування дерноутворювальних трав (переважно багаторічних злаків) або одернування
      </term>
      <term name="гальмовий шлях">
        відстань, що проходить транспортний засіб під час екстреного гальмування з початку здійснення впливу на орган керування гальмовою системою (педаль, рукоятку) до місця його зупинки
      </term>
      <term name="головна дорога">
        дорога з покриттям відносно ґрунтової або та, що позначається знаками 1.22 , 1.23.1 , 1.23.2 , 1.23.3 , 1.23.4 , 2.3 . Наявність на другорядній дорозі покриття безпосередньо перед перехрестям не прирівнює її за значенням до перехрещуваної;
      </term>
      <term name="дати дорогу">
        вимога до учасника дорожнього руху не продовжувати або не відновлювати рух, не здійснювати будь-яких маневрів (за винятком вимоги звільнити займану смугу руху), якщо це може примусити інших учасників дорожнього руху, які мають перевагу, змінити напрямок руху або швидкість;
      </term>
      <term name="денні ходові вогні">
        зовнішні світлові прилади білого кольору, передбачені конструкцією транспортного засобу, установлені спереду транспортного засобу і призначені для покращення видимості транспортного засобу під час його руху у світлий час доби
      </term>
      <term name="дозволена максимальна маса">
        маса спорядженого транспортного засобу з вантажем, водієм і пасажирами, що встановлена технічною характеристикою транспортного засобу як максимально допустима. Дозволена максимальна маса автопоїзда — це сума дозволеної максимально допустимої маси кожного транспортного засобу, що входить до складу автопоїзда
      </term>
      <term name="дорожньо-транспортна пригода">
        подія, що сталася під час руху транспортного засобу, внаслідок якої загинули або поранені люди чи завдані матеріальні збитки;
      </term>
      <term name="дорожні роботи">
        роботи, пов’язані з будівництвом, реконструкцією, ремонтом чи утриманням автомобільної дороги (вулиці), штучних споруд, споруд дорожнього водовідводу, інженерного облаштування, встановленням (ремонтом, заміною) технічних засобів організації дорожнього руху;
      </term>
      <term name="дорожні умови">
        сукупність факторів, що характеризують (з урахуванням пори року, періоду доби, атмосферних явищ, освітленості дороги) видимість у напрямку руху, стан поверхні проїзної частини (чистота, рівність, шорсткість, зчеплення), а також її ширину, величину похилів на спусках і підйомах, віражів і заокруглень, наявність тротуарів або узбіч, засобів організації дорожнього руху та їх стан;
      </term>
      <term name="дорожня обстановка">
        сукупність факторів, що характеризуються дорожніми умовами, наявністю перешкод на певній ділянці дороги, інтенсивністю і рівнем організації дорожнього руху (наявність дорожньої розмітки, дорожніх знаків, дорожнього обладнання, світлофорів та їх стан), які повинен ураховувати водій під час вибору швидкості, смуги руху та прийомів керування транспортним засобом;
      </term>
      <term name="експлуатація транспортного состава">
        транспортування тягачем причепа згідно з інструкцією щодо його використання (відповідність причепа тягачу, наявність страхового з'єднання, єдиної системи сигналізації, освітлення тощо)
      </term>
      <term name="естакада">
        інженерна споруда для руху транспортних засобів та (або) пішоходів, підняття однієї дороги над іншою у місці їх перетину, а також для створення дороги на певній висоті, яка не має з'їздів на іншу дорогу;
      </term>
      <term name="житлова зона">
        дворові території, а також частини населених пунктів, позначені дорожнім знаком 5.31
      </term>
      <term name="залізничний переїзд">
        перехрещення дороги із залізничними коліями на одному рівні;
      </term>
      <term name="засліплення">
        фізіологічний стан водія внаслідок дії світла на його зір, коли водій об'єктивно не має можливості виявити перешкоди чи розпізнати межі елементів дороги на мінімальній відстані;
      </term>
      <term name="зупинка">
        припинення руху транспортного засобу на час до 5 хвилин або більше, якщо це необхідно для посадки (висадки) пасажирів чи завантаження (розвантаження) вантажу, виконання вимог цих Правил (надання переваги в русі, виконання вимог регулювальника, сигналів світлофора тощо);
      </term>
      <term name="колона пішоходів">
        організована група людей, які рухаються по проїзній частині в одному напрямку;
      </term>
      <term name="колона транспортних засобів">
        організована група з трьох і більше транспортних засобів, що разом рухаються в одному напрямку безпосередньо один за одним з постійно увімкненим ближнім світлом фар
      </term>
      <term name="край проїзної частини (для нерейкових транспортних засобів)">
        видима умовна чи позначена дорожньою розміткою лінія на проїзній частині в місці її прилягання до узбіччя, тротуару, газону, розділювальної смуги, смуги для руху трамваїв, велосипедної або пішохідної доріжки;
      </term>
      <term name="крайнє положення на проїзній частині">
        положення транспортного засобу на відстані від краю проїзної частини (середини проїзної частини або розділювальної смуги), яка не дає можливості рухатися попутному транспортному засобу (у тому числі двоколісному) ще ближче до краю проїзної частини (середини проїзної частини або розділювальної смуги);
      </term>
      <term name="легковий автомобіль">
        автомобіль з кількістю місць для сидіння не більше дев'яти, з місцем водія включно, який за своєю конструкцією та обладнанням призначений для перевезення пасажирів та їхнього багажу із забезпеченням необхідного комфорту та безпеки;
      </term>
      <term name="маневрування (маневр)">
        початок руху, перестроювання транспортного засобу в русі з однієї смуги на іншу, поворот праворуч чи ліворуч, розворот, з’їзд з проїзної частини, рух заднім ходом;
      </term>
      <term name="маршрутні транспортні засоби (транспортні засоби загального користування)">
        автобуси, мікроавтобуси, тролейбуси, трамваї і таксі, що рухаються за встановленими маршрутами та мають визначені місця на дорозі для посадки (висадки) пасажирів;
      </term>
      <term name="механічний транспортний засіб">
        транспортний засіб, що приводиться в рух з допомогою двигуна. Цей термін поширюється на трактори, самохідні машини і механізми, а також тролейбуси та транспортні засоби з електродвигуном потужністю понад 3 кВт;
      </term>
      <term name="мікроавтобус">
        одноповерховий автобус з кількістю місць для сидіння не більше сімнадцяти з місцем водія включно;
      </term>
      <term name="міст">
        споруда, призначена для руху через річку, яр та інші перешкоди, межами якої є початок і кінець пролітних споруд;
      </term>
      <term name="мопед">
        двоколісний транспортний засіб, що має двигун з робочим об'ємом до 50 куб. см або електродвигун потужністю до 4 кВт;
      </term>
      <term name="мотоцикл">
        двоколісний механічний транспортний засіб з боковим причепом або без нього, що має двигун з робочим об'ємом 50 куб. см і більше. До мотоциклів прирівнюються моторолери, мотоколяски, триколісні та інші механічні транспортні засоби, дозволена максимальна маса яких не перевищує 400 кг;
      </term>
      <term name="населений пункт">
        забудована територія, в'їзди на яку і виїзди з якої позначаються дорожніми знаками 5.45 Знак 5.45 "Населений пункт", 5.46 Знак 5.46 "Кінець населеного пункта", 5.47 Знак 5.47 "Населений пункт", 5.48 Знак 5.48 "Кінець населеного пункта";
      </term>
      <term name="небезпека для руху">
        зміна дорожньої обстановки (у тому числі поява рухомого об'єкта, який наближається до смуги руху транспортного засобу чи перетинає її) або технічного стану транспортного засобу, яка загрожує безпеці дорожнього руху і змушує водія негайно зменшити швидкість або зупинитися. Окремим випадком небезпеки для руху є рух у межах смуги транспортного засобу іншого транспортного засобу назустріч загальному потоку;
      </term>
      <term name="недостатня видимість">
        видимість дороги в напрямку руху менше 300 м у сутінках, в умовах туману, дощу, снігопаду тощо;
      </term>
      <term name="обгін">
        випередження одного або кількох транспортних засобів, пов'язане з виїздом на смугу зустрічного руху;
      </term>
      <term name="обмежена оглядовість">
        видимість дороги в напрямку руху, яка обмежена геометричними параметрами дороги, придорожніми інженерними спорудами, насадженнями та іншими об'єктами, а також транспортними засобами;
      </term>
      <term name="оглядовість">
        об'єктивна можливість бачити дорожню обстановку з місця водія;
      </term>
      <term name="острівець безпеки">
        технічний засіб регулювання дорожнього руху на наземних пішохідних переходах, конструктивно виділений над проїзною частиною дороги та призначений як захисний елемент для зупинки пішоходів під час переходу проїзної частини дороги. До острівця безпеки належить частина розділювальної смуги, через яку пролягає пішохідний перехід;
      </term>
      <term name="пасажир">
        особа, яка користується транспортним засобом і знаходиться в ньому, але не причетна до керування ним;
      </term>
      <term name="перевага">
        право на першочерговий рух стосовно інших учасників дорожнього руху;
      </term>
      <term name="перевезення організованих груп дітей">
        дночасне перевезення десяти і більше дітей з керівником, відповідальним за їх супроводження під час поїздки (на групу з тридцяти і більше дітей призначається додатково медичний працівник);
      </term>
      <term name="перешкода для руху">
        нерухомий об’єкт у межах смуги руху транспортного засобу або об’єкт, що рухається попутно в межах цієї смуги (за винятком транспортного засобу, що рухається назустріч загальному потоку транспортних засобів) і змушує водія маневрувати або зменшувати швидкість аж до зупинки транспортного засобу;
      </term>
      <term name="пішохід">
        особа, яка бере участь у дорожньому русі поза транспортними засобами і не виконує на дорозі будь-яку роботу. До пішоходів прирівнюються також особи, які рухаються в інвалідних колясках без двигуна, ведуть велосипед, мопед, мотоцикл, везуть санки, візок, дитячу чи інвалідну коляску;
      </term>
      <term name="пішохідна доріжка">
        доріжка з покриттям, призначена для руху пішоходів, виконана в межах дороги чи поза нею і позначена знаком 4.13 Знак 4.13 "Пішохідна доріжка";
      </term>
      <term name="пішохідний перехід">
        ділянка проїзної частини або інженерна споруда, призначена для руху пішоходів через дорогу. Пішохідні переходи позначаються дорожніми знаками 5.35.1 , 5.35.2 , 5.36.1 , 5.36.2 , 5.37.1 , 5.37.2 , дорожньою розміткою 1.14.1, 1.14.2, 1.14.3, пішохідними світлофорами. За відсутності дорожньої розмітки межі пішохідного переходу визначаються відстанню між дорожніми знаками або пішохідними світлофорами, а на перехресті за відсутності пішохідних світлофорів, дорожніх знаків та розмітки — шириною тротуарів чи узбіч;
        Регульованим вважається пішохідний перехід, рух по якому регулюється світлофором чи регулювальником, нерегульованим — пішохідний перехід, на якому немає регулювальника, світлофори відсутні або вимкнені чи працюють у режимі миготіння жовтого сигналу;
      </term>
      <term name="прилегла територія">
        територія, що прилягає до краю проїзної частини та не призначена для наскрізного проїзду, а лише для в’їзду до дворів, на стоянки, автозаправні станції, будівельні майданчики тощо або виїзду з них;
      </term>
      <term name="причіп">
        транспортний засіб, призначений для руху тільки в з’єднанні з іншим транспортним засобом. До цього виду транспортних засобів належать також напівпричепи і причепи-розпуски;
      </term>
      <term name="проїзна частина">
        елемент дороги, призначений для руху нерейкових транспортних засобів. Дорога може мати декілька проїзних частин, межами яких є розділювальні смуги;
      </term>
      <term name="регулювальник">
        працівник міліції, що виконує регулювання дорожнього руху у форменому одязі підвищеної видимості з елементами із світлоповертального матеріалу за допомогою жезлу, свистка. До регулювальника прирівнюються працівники військової інспекції безпеки дорожнього руху, дорожньо-експлуатаційної служби, черговий на залізничному переїзді, поромній переправі, які мають відповідне посвідчення та нарукавну пов’язку, жезл, диск з червоним сигналом чи світлоповертачем, червоний ліхтар або прапорець та виконують регулювання у форменому одязі;
      </term>
      <term name="рейковий транспортний засіб">
        трамвай та платформи із спеціальним обладнанням, що рухаються трамвайними коліями. Усі інші транспортні засоби, що беруть участь у дорожньому русі, вважаються нерейковими;
      </term>
      <term name="розділювальна смуга">
        виділений конструктивно або за допомогою суцільних ліній дорожньої розмітки 1.1 і 1.2 елемент автомобільної дороги, який розділяє суміжні проїзні частини. Розділювальна смуга не призначена для руху або стоянки транспортних засобів. За наявності на розділювальній смузі тротуару по ньому дозволяється рух пішоходів;
      </term>
      <term name="смуга руху">
        поздовжня смуга на проїзній частині завширшки щонайменше 2,75 м, що позначена або не позначена дорожньою розміткою і призначена для руху нерейкових транспортних засобів;
      </term>
      <term name="стоянка">
        припинення руху транспортного засобу на час, більший ніж 5 хвилин, з причин, не пов’язаних з необхідністю виконання вимог цих Правил, посадкою (висадкою) пасажирів, завантаженням (розвантаженням) вантажу;
      </term>
      <term name="темна пора доби">
        частина доби від заходу до сходу сонця;
      </term>
      <term name="трамвайна колія">
        елемент дороги, призначений для руху рейкових транспортних засобів, який обмежується по ширині спеціально виділеним вимощенням трамвайної лінії або дорожньою розміткою. По трамвайній колії допускається рух нерейкових транспортних засобів відповідно до розділу 11 цих Правил;
      </term>
      <term name="транспортний засіб">
        пристрій, призначений для перевезення людей і (або) вантажу, а також встановленого на ньому спеціального обладнання чи механізмів;
      </term>
      <term name="тротуар">
        елемент дороги, призначений для руху пішоходів, який прилягає до проїзної частини або відокремлений від неї газоном;
      </term>
      <term name="узбіччя">
        виділений конструктивно або суцільною лінією дорожньої розмітки елемент автомобільної дороги, який прилягає безпосередньо до зовнішнього краю проїзної частини, розташований з нею на одному рівні та не призначений для руху транспортних засобів, крім випадків, передбачених цими Правилами. Узбіччя може використовуватися для зупинки і стоянки транспортних засобів, руху пішоходів, мопедів, велосипедів (за відсутності тротуарів, пішохідних, велосипедних доріжок або у разі неможливості пересуватися по них), гужових возів (саней);
      </term>
      <term name="учасник дорожнього руху">
        особа, яка бере безпосередню участь у процесі руху на дорозі як пішохід, водій, пасажир, погонич тварин;
      </term>
      <term name="шляхопровід">
        інженерна споруда мостового типу над іншою дорогою (залізницею) в місці їх перетину, що забезпечує рух по ній на різних рівнях та дає можливість з’їзду на іншу дорогу.
      </term>
    </rule>
  </section>
  <section number="2" name="Обов'язки і права водіїв механічних транспортних засобів">
    <rule number="2.1">
      Водій механічного транспортного засобу повинен мати при собі:
      a)  посвідчення на право керування транспортним засобом відповідної категорії;
      б)	реєстраційний документ на транспортний засіб (для транспортних засобів Збройних Сил, Національної Гвардії, Держприкордонслужби, Держспецтрансслужби, Держспецзв’язку, Оперативно-рятувальної служби цивільного захисту — технічний талон);
      в)	у разі встановлення на транспортних засобах проблискових маячків і (або) спеціальних звукових сигнальних пристроїв — дозвіл, виданий Державтоінспекцією МВС;
      г)	на маршрутних транспортних засобах — схему маршруту та розклад руху; на великовагових і великогабаритних транспортних засобах та транспортних засобах, що здійснюють дорожнє перевезення небезпечних вантажів, — документацію відповідно до вимог спеціальних правил;
      ґ)	поліс (сертифікат) обов’язкового страхування цивільно-правової відповідальності власників наземних транспортних засобів. Водії, які відповідно до законодавства звільняються від обов’язкового страхування цивільно-правової відповідальності власників наземних транспортних засобів на території України, повинні мати при собі відповідні підтвердні документи (посвідчення);
    </rule>
    <rule number="2.2">
      Власник транспортного засобу, а також особа, яка використовує такий транспортний засіб на законних підставах, можуть передавати керування транспортним засобом іншій особі, що має при собі посвідчення на право керування транспортним засобом відповідної категорії.
      Власник транспортного засобу може передавати такий засіб у користування іншій особі, що має посвідчення водія на право керування транспортним засобом відповідної категорії, передавши їй реєстраційний документ на цей транспортний засіб.
    </rule>
    <rule number="2.3">
      Для забезпечення безпеки дорожнього руху водій зобов’язаний:
      a)	перед виїздом перевірити і забезпечити технічно справний стан і комплектність транспортного засобу, правильність розміщення та кріплення вантажу;
      б)	бути уважним, стежити за дорожньою обстановкою, відповідно реагувати на її зміну, стежити за правильністю розміщення та кріплення вантажу, технічним станом транспортного засобу і не відволікатися від керування цим засобом у дорозі;
      в)	на автомобілях, обладнаних засобами пасивної безпеки (підголовники, ремені безпеки), користуватися ними і не перевозити пасажирів, не пристебнутих ременями безпеки. Дозволяється не пристібатися особі, яка навчає водінню, якщо за кермом учень, а в населених пунктах, крім того, водіям-інвалідам, водіям і пасажирам оперативних та спеціальних транспортних засобів і таксі;
      г)	під час руху на мотоциклі і мопеді бути в застебнутому мотошоломі і не перевозити пасажирів без застебнутих мотошоломів;
      ґ)	не забруднювати проїзну частину та смугу відведення автомобільних доріг;
      д)	не створювати своїми діями загрози безпеці дорожнього руху;
      е)	повідомляти дорожньо-експлуатаційним організаціям або Державтоінспекції про виявлені факти створення перешкод для дорожнього руху;
      є)	не вчиняти дій, внаслідок яких може бути пошкоджено автомобільні дороги та їх складові, а також завдано шкоди користувачам.
    </rule>
    <rule number="2.4">
      На вимогу працівника міліції водій повинен зупинитися з дотриманням вимог цих Правил, а також:
      a)	пред'явити для перевірки документи, зазначені в пункті 2.1;
      б)	дати можливість перевірити номери агрегатів і комплектність транспортного засобу;
      в)	дати можливість оглянути транспортний засіб відповідно до законодавства за наявності на те законних підстав, у тому числі провести з використанням спеціальних пристроїв (приладів) перевірку технічного стану транспортних засобів, які відповідно до законодавства підлягають обов’язковому технічному контролю.
    </rule>
    <rule number="2.4.1">
      У місці здійснення габаритно-вагового контролю на вимогу працівника пункту габаритно-вагового контролю або працівника МВС водій вантажного автомобіля (в тому числі механічного транспортного засобу) повинен зупинитися з дотриманням вимог цих Правил, а також:
      a)	передати для перевірки документи, зазначені в підпунктах «а», «б» і «г» пункту 2.1 цих Правил;
      б)	надати транспортний засіб та причіп (за наявності) для вагового та/або габаритного контролю відповідно до встановленої процедури.
    </rule>
    <rule number="2.4.2">
      У разі виявлення під час здійснення габаритно-вагового контролю невідповідності фактичних вагових та/або габаритних параметрів установленим нормам і правилам рух такого транспортного засобу та/або причепу забороняється до отримання в установленому порядку дозволу на проїзд автомобільними дорогами транспортних засобів, вагові або габаритні параметри яких перевищують нормативні, про що складається відповідний акт.
    </rule>
    <rule number="2.5">
      Водій повинен на вимогу працівника міліції пройти в установленому порядку медичний огляд для визначення стану алкогольного сп’яніння, впливу наркотичних чи токсичних речовин.
    </rule>
    <rule number="2.6">
      За рішенням уповноваженої на те посадової особи Державтоінспекції, за наявності на те підстав, водій зобов’язаний пройти позачерговий медичний огляд з метою визначення здатності безпечно керувати транспортним засобом і перевірку знання цих Правил та навичок водіння.
    </rule>
    <rule number="2.7">
      Водій, крім водіїв транспортних засобів дипломатичних та інших представництв іноземних держав, міжнародних організацій, оперативних і спеціальних транспортних засобів, повинен надавати транспортний засіб:
      a)	працівникам міліції та охорони здоров’я для доставки до найближчого лікувального закладу осіб, які потребують негайної медичної допомоги;
      б)	працівникам міліції для виконання непередбачених і невідкладних службових обов’язків, пов’язаних із переслідуванням правопорушників, доставкою їх у міліцію, та для транспортування пошкоджених транспортних засобів.
      Примітки:
      Для транспортування пошкоджених транспортних засобів залучаються лише вантажні автомобілі.
      Особа, яка скористалася транспортним засобом, повинна видати довідку із зазначенням пройденої відстані, тривалості поїздки, свого прізвища, посади, номера посвідчення, повного найменування свого підрозділу чи організації.
    </rule>
    <rule number="2.8">